
-- ACESSANDO O BD
USE DB_T04703_CEZAR_SILVA;

DROP TABLE IF EXISTS TB_CLIENTES_T;
DROP TABLE IF EXISTS TB_PEDIDOS_T;

-- TABELA CLIENTES
CREATE TABLE TB_CLIENTES_T (
	id_cliente INT AUTO_INCREMENT PRIMARY KEY,
    nome_cliente VARCHAR(100) NOT NULL
);

-- INSERT NA TABELA DE CLIENTES
INSERT INTO TB_CLIENTES_T (nome_cliente)
VALUES ('JOAO'), 
       ('MARIA'),
       ('JOSE');

-- CONSULTA A TABELA DE CLIENTES
SELECT * FROM TB_CLIENTES_T;

-- CRIANDO A TABELA DE PEDIDOS
CREATE TABLE TB_PEDIDOS_T(
	id_pedido INT AUTO_INCREMENT PRIMARY KEY,
    id_cliente_pedido INT NOT NULL,
    data_venda DATE,
    FOREIGN KEY (id_cliente_pedido) REFERENCES TB_CLIENTES_T(id_cliente)
);

INSERT INTO TB_PEDIDOS_T (id_cliente_pedido, data_venda)
VALUES (1, '2026-05-21'),
       (2, '2026-05-22'),
       (3, '2026-05-23');

-- CONSULTA A TABELA DE PEDIDOS       
SELECT * FROM TB_PEDIDOS_T;

INSERT INTO TB_PEDIDOS_T (id_cliente_pedido, data_venda)
VALUES (4, '2026-05-21');

DELETE FROM TB_CLIENTES_T
WHERE id_cliente = 3;






