-- NEGOCIO PAPELARIA
-- TABELAS: PRODUTOS, VENDAS E FORNECEDORES

-- ACESSANDO O BD
USE DB_T04703_CEZAR_SILVA;

-- CRIANDO A TABELA FORNECEDOR
CREATE TABLE TB_FORNECEDOR (
	id_fornecedor INT AUTO_INCREMENT PRIMARY KEY,
	nome_fornecedor VARCHAR(150),
    telefone_fornecedor VARCHAR(20)
);

-- INSERIR DADOS NA TABELA DE FORNECEDORES
INSERT INTO TB_FORNECEDOR (nome_fornecedor, telefone_fornecedor)
VALUES ('BIC', '(11) 91234-5678'),
       ('FABER CASTEL', '(12) 96666-3333'),
       ('KIDS', '(17) 97777-8989');

-- CRIANDO A TABELA DE PRODUTOS
CREATE TABLE TB_PRODUTOS (
	id_produto INT AUTO_INCREMENT PRIMARY KEY,
    nome_produto VARCHAR(100) NOT NULL,
    quantidade INT NOT NULL,
    id_fornecedor INT NOT NULL,
    FOREIGN KEY (id_fornecedor) REFERENCES TB_FORNECEDOR(id_fornecedor)
);

-- INSERINDO REGISTROS NA MINHA TABELA DE PRODUTOS
INSERT INTO TB_PRODUTOS (nome_produto, quantidade, id_fornecedor)
VALUES ('CANETA', 500, 1),
	   ('LAPISEIRA', 120, 1),
       ('LAPIS DE COR', 500, 2),
       ('BORRACHA', 150, 3);

-- SIMULANDO O CADASTRO DE UM PRODUTO, CUJO O FORNECEDOR NAO EXISTE;
INSERT INTO TB_PRODUTOS (nome_produto, quantidade, id_fornecedor)
VALUES ('REGUA', 100, 4);

-- CRIANDO A TABELA DE VENDAS
CREATE TABLE TB_VENDAS (
	id_venda INT AUTO_INCREMENT PRIMARY KEY,
    id_produto INT NOT NULL,
    data_venda DATE NOT NULL
);

INSERT INTO TB_VENDAS (id_produto, data_venda)
VALUES (1, '2026-08-21'),
       (2, '2026-08-22'),
       (3, '2026-08-23');


-- CONSULTA TABELA FORNECEDOR
SELECT * FROM TB_FORNECEDOR;

-- CONSULTA A TABELA PRODUTOS
SELECT * FROM TB_PRODUTOS;

-- CONSULTAR INFORMAÇÕES DA TABELA DE VENDAS
SELECT * FROM TB_VENDAS;










-- CONSULTA TABELA FORNECEDOR
SELECT * FROM TB_FORNECEDOR;





