-- CONSULTANDO BD EXISTENTES
SHOW DATABASES;

-- CRIANDO UM BANCO DE DADOS
CREATE DATABASE DB_T04703_CEZAR_SILVA;

-- ACESSANDO O BD
USE DB_T04703_CEZAR_SILVA;

-- CRIANDO A TABELA 
CREATE TABLE TB_LIVROS (
	id_livro INT AUTO_INCREMENT PRIMARY KEY,
    titulo_livro VARCHAR(150),
    autor VARCHAR(120),
    ano_publicacao INT,
    genero VARCHAR(50)
);

/*COMENTARIOS LONGOS*/
-- INSERINDO REGISTROS NA TABELA LIVROS
INSERT INTO TB_LIVROS (titulo_livro, autor, ano_publicacao, genero)
 VALUES ('Dom Casmurro', 'Machado de Assis', 1899, 'Romance');
 
-- INSERINDO MULTIPLOS REGISTROS COM APENAS 1 "VALUES"
INSERT INTO TB_LIVROS (titulo_livro, autor, ano_publicacao, genero)
VALUES ('Cem anos de Solidão', 'Gabriel Garcia Marquz', 1967, 'Realismo mágico'),
       ('O pequeno Principe', 'Antonie de Saint-Exupery', 1943, 'Fabula/ Literatura Infantil'), 
       ('O Hobbit', 'J.R.R. Tolkien', 1937, 'Fantasia');

-- CONSULTANDO OS REGISTROS DA TABELA LIVROS
SELECT * FROM TB_LIVROS;

-- ORDENANDO AS INFORMAÇÕES DO RESULTADO DE UMA CONSULTA
-- POR ORDEM ALFABETICA - ASC
SELECT * FROM TB_LIVROS
ORDER BY autor ASC;


-- ORDENANDO AS INFORMAÇÕES DO RESULTADO DE UMA CONSULTA
-- POR ORDEM ALFABETICA - DESC
SELECT * FROM TB_LIVROS
ORDER BY autor DESC;


-- LIMIT
SELECT * FROM TB_LIVROS
LIMIT 2;

-- LIKE
-- COMEÇA COM A LETRA R
SELECT * FROM TB_LIVROS
WHERE genero LIKE 'R%';

-- TERMINA COM A LETRA O
SELECT * FROM TB_LIVROS
WHERE genero LIKE '%o';


-- QUALQUER POSIÇÃO DO TEXTO
-- DEVE CONTER A LETRA 'R'
SELECT * FROM TB_LIVROS
WHERE genero LIKE '%literatura%';


































